# Generated by Django 4.2.6 on 2023-10-31 15:06

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group', models.CharField(max_length=256)),
                ('units', models.IntegerField()),
                ('degree', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('selection_start_time', django_jalali.db.models.jDateTimeField()),
                ('selection_end_time', django_jalali.db.models.jDateTimeField()),
                ('classes_start_time', django_jalali.db.models.jDateTimeField()),
                ('classes_end_time', django_jalali.db.models.jDateTimeField()),
                ('update_start_time', django_jalali.db.models.jDateTimeField()),
                ('update_end_time', django_jalali.db.models.jDateTimeField()),
                ('emergency_cancellation_end_time', models.DateTimeField()),
                ('exams_start_time', django_jalali.db.models.jDateField()),
                ('term_end_time', django_jalali.db.models.jDateField()),
            ],
        ),
    ]
