# Generated by Django 4.2.6 on 2023-11-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTakenCourseReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.BooleanField(default=False)),
                ('add_courses', models.ManyToManyField(blank=True, related_name='update_taken_course_add', to='course.course')),
                ('del_courses', models.ManyToManyField(blank=True, related_name='update_taken_course_del', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_taken_course_student', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='TermDropReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_descr', models.TextField(blank=True, null=True)),
                ('educational_deputy_descr', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_drop_req_student', to='accounts.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_drop_req_term', to='course.term')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCourseReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_text', models.TextField()),
                ('result_text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course_course', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course_student', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_student', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentVerificationReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_verification_file', models.FileField(upload_to='')),
                ('issuance_certificate_place', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_verification_req_student', to='accounts.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_verification_req_term', to='course.term')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDropReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_descr', models.TextField(blank=True, null=True)),
                ('educational_deputy_descr', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_drop_req_course', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_drop_req_student', to='accounts.student')),
            ],
        ),
    ]
